//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDXLSharp.EDXLRMLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDXLSharp.EDXLRMLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;urn:oasis:names:tc:ciq:ct:3&quot; targetNamespace=&quot;urn:oasis:names:tc:ciq:ct:3&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;xs:annotation&gt;
        ///		&lt;xs:documentation&gt; 
        ///		Specification Name: OASIS CIQ TC - CIQ V3.0
        ///		Description: Defines the W3C schema with commonly used types in the name, address and party schemas
        ///		(Using XML Schema based standard code list/enumeration mechanism - OPTION 1  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonTypes {
            get {
                return ResourceManager.GetString("CommonTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	 xmlns:rmsg=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    targetNamespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///	 xmlns:rm=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///    xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    attributeFormDefault=&quot;unqualified&quot;&gt;
        ///  &lt;xsd:import namespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///  schemaLocation=&quot;EDXL-RMCommonTypes.xsd&quot;/&gt;
        ///  &lt;!-- This schema describes the struc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDXL_RMCommitResource {
            get {
                return ResourceManager.GetString("EDXL_RMCommitResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///            xmlns:xnal=&quot;urn:oasis:names:tc:ciq:xnal:3&quot;
        ///            xmlns:xnl=&quot;urn:oasis:names:tc:ciq:xnl:3&quot;
        ///            xmlns:xal=&quot;urn:oasis:names:tc:ciq:xal:3&quot;
        ///            xmlns:xpil=&quot;urn:oasis:names:tc:ciq:xpil:3&quot;
        ///            xmlns:geo-oasis=&quot;urn:oasis:names:tc:emergency:EDXL:HAVE:1.0:geo-oasis&quot;
        ///            xmlns=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///  targetNamespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///   elementFormDefault=&quot;qua [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDXL_RMCommonTypes {
            get {
                return ResourceManager.GetString("EDXL_RMCommonTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    xmlns:rmsg=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        /// 	 targetNamespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    xmlns:rm=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///    xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    attributeFormDefault=&quot;unqualified&quot;&gt;
        ///  &lt;xsd:import namespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        /// schemaLocation=&quot;EDXL-RMCommonTypes.xsd&quot;/&gt;
        ///  &lt;!-- This schema describes the str [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDXL_RMOfferUnsolicitedResource {
            get {
                return ResourceManager.GetString("EDXL_RMOfferUnsolicitedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    xmlns:rmsg=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    targetNamespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    xmlns:rm=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///    xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    attributeFormDefault=&quot;unqualified&quot;&gt;
        ///  &lt;xsd:import namespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        /// schemaLocation=&quot;EDXL-RMCommonTypes.xsd&quot;/&gt;
        ///  &lt;!-- This schema is the base refe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDXL_RMReference {
            get {
                return ResourceManager.GetString("EDXL_RMReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    xmlns:rmsg=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        /// 	 targetNamespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    xmlns:rm=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///    xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    attributeFormDefault=&quot;unqualified&quot;&gt;
        ///  &lt;xsd:import namespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///    schemaLocation=&quot;EDXL-RMCommonTypes.xsd&quot;/&gt;
        ///  &lt;!-- This schema describes the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDXL_RMReleaseResource {
            get {
                return ResourceManager.GetString("EDXL_RMReleaseResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    xmlns:rmsg=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        /// 	 targetNamespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    xmlns:rm=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///    xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    attributeFormDefault=&quot;unqualified&quot;&gt;
        ///  &lt;xsd:import namespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///   schemaLocation=&quot;EDXL-RMCommonTypes.xsd&quot;/&gt;
        ///  &lt;!-- This schema describes the s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDXL_RMReportResourceDeploymentStatus {
            get {
                return ResourceManager.GetString("EDXL_RMReportResourceDeploymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    xmlns:rmsg=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        /// 	 targetNamespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    xmlns:rm=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///    xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    attributeFormDefault=&quot;unqualified&quot;&gt;
        ///  &lt;xsd:import namespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///   schemaLocation=&quot;EDXL-RMCommonTypes.xsd&quot;/&gt;
        ///  &lt;!-- This schema describes the s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDXL_RMRequestExtendedDeploymentDuration {
            get {
                return ResourceManager.GetString("EDXL_RMRequestExtendedDeploymentDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    xmlns:rmsg=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        /// 	 targetNamespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    xmlns:rm=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///    xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    attributeFormDefault=&quot;unqualified&quot;&gt;
        ///  &lt;xsd:import namespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///schemaLocation=&quot;EDXL-RMCommonTypes.xsd&quot;/&gt;
        ///  &lt;!-- This schema describes the stru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDXL_RMRequestInformation {
            get {
                return ResourceManager.GetString("EDXL_RMRequestInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    xmlns:rmsg=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        /// 	 targetNamespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    xmlns:rm=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///    xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    attributeFormDefault=&quot;unqualified&quot;&gt;
        ///  &lt;xsd:import namespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///    schemaLocation=&quot;EDXL-RMCommonTypes.xsd&quot;/&gt;
        ///  &lt;!-- This schema describes the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDXL_RMRequestQuote {
            get {
                return ResourceManager.GetString("EDXL_RMRequestQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    xmlns:rmsg=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        /// 	 targetNamespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    xmlns:rm=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        /// 	 xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///  &lt;xsd:import namespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///   schemaLocation=&quot;EDXL-RMCommonTypes.xsd&quot;/&gt;
        ///  &lt;!-- This schema describes the structu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDXL_RMRequestResource {
            get {
                return ResourceManager.GetString("EDXL_RMRequestResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    xmlns:rmsg=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    targetNamespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    xmlns:rm=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///    xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    attributeFormDefault=&quot;unqualified&quot;&gt;
        ///  &lt;xsd:import namespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///   schemaLocation=&quot;EDXL-RMCommonTypes.xsd&quot;/&gt;
        ///  &lt;!-- This schema describes the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDXL_RMRequestResourceDeploymentStatus {
            get {
                return ResourceManager.GetString("EDXL_RMRequestResourceDeploymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    xmlns:rmsg=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    targetNamespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    xmlns:rm=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///    xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    attributeFormDefault=&quot;unqualified&quot;&gt;
        ///  &lt;xsd:import namespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///  schemaLocation=&quot;EDXL-RMCommonTypes.xsd&quot;/&gt;
        ///  &lt;!-- This schema describes the s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDXL_RMRequestReturn {
            get {
                return ResourceManager.GetString("EDXL_RMRequestReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    xmlns:rmsg=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///	 targetNamespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    xmlns:rm=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///    xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    attributeFormDefault=&quot;unqualified&quot;&gt;
        ///  &lt;xsd:import namespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        /// schemaLocation=&quot;EDXL-RMCommonTypes.xsd&quot;/&gt;
        ///  &lt;!-- This schema describes the stru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDXL_RMRequisitionResource {
            get {
                return ResourceManager.GetString("EDXL_RMRequisitionResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    xmlns:rmsg=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    targetNamespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    xmlns:rm=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///    xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    attributeFormDefault=&quot;unqualified&quot;&gt;
        ///  &lt;xsd:import namespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///   schemaLocation=&quot;EDXL-RMCommonTypes.xsd&quot;/&gt;
        ///  &lt;!-- This schema describes the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDXL_RMResponseToRequestExtendedDeploymentDuration {
            get {
                return ResourceManager.GetString("EDXL_RMResponseToRequestExtendedDeploymentDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    xmlns:rmsg=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        /// 	 targetNamespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    xmlns:rm=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///    xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    attributeFormDefault=&quot;unqualified&quot;&gt;
        ///  &lt;xsd:import namespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///   schemaLocation=&quot;EDXL-RMCommonTypes.xsd&quot;/&gt;
        ///  &lt;!-- This schema describes the s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDXL_RMResponseToRequestInformation {
            get {
                return ResourceManager.GetString("EDXL_RMResponseToRequestInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    xmlns:rmsg=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        /// 	 targetNamespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    xmlns:rm=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///    xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    attributeFormDefault=&quot;unqualified&quot;&gt;
        ///  &lt;xsd:import namespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///schemaLocation=&quot;EDXL-RMCommonTypes.xsd&quot;/&gt;
        ///  &lt;!-- This schema describes the stru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDXL_RMResponseToRequestQuote {
            get {
                return ResourceManager.GetString("EDXL_RMResponseToRequestQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    xmlns:rmsg=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        /// 	 targetNamespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    xmlns:rm=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///    xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    attributeFormDefault=&quot;unqualified&quot;&gt;
        ///  &lt;xsd:import namespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///schemaLocation=&quot;EDXL-RMCommonTypes.xsd&quot;/&gt;
        ///  &lt;!-- This schema describes the stru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDXL_RMResponseToRequestResource {
            get {
                return ResourceManager.GetString("EDXL_RMResponseToRequestResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    xmlns:rmsg=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        /// 	 targetNamespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg&quot;
        ///    xmlns:rm=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///    xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    attributeFormDefault=&quot;unqualified&quot;&gt;
        ///  &lt;xsd:import namespace=&quot;urn:oasis:names:tc:emergency:EDXL:RM:1.0&quot;
        ///   schemaLocation=&quot;EDXL-RMCommonTypes.xsd&quot;/&gt;
        ///  &lt;!-- This schema describes the s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDXL_RMResponseToRequestReturn {
            get {
                return ResourceManager.GetString("EDXL_RMResponseToRequestReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XMLSpy v2007 rel. 3 (http://www.altova.com) by Sukumar Dwarkanath (private) --&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:oasis=&quot;urn:oasis:names:tc:emergency:EDXL:HAVE:1.0:geo-oasis&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; targetNamespace=&quot;urn:oasis:names:tc:emergency:EDXL:HAVE:1.0:geo-oasis&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot; version=&quot;1.0&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://www.opengis.net/gml&quot; schemaLoc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string geo_oasis {
            get {
                return ResourceManager.GetString("geo_oasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; targetNamespace=&quot;http://www.opengis.net/gml&quot; elementFormDefault=&quot;qualified&quot; version=&quot;3.1.1&quot;&gt;
        ///   &lt;annotation&gt;
        ///      &lt;documentation&gt;GML Subset schema for gml:Point,gml:LineString,gml:CircleByCentrePoint,gml:Curve,gml:Polygon,gml:LinearRing,gml:Envelope,  written by gmlSubset.xslt. &lt;/documentation&gt;
        ///   &lt;/annotation&gt;
        ///   &lt;import namespace=&quot;h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gml_oasis {
            get {
                return ResourceManager.GetString("gml_oasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;urn:oasis:names:tc:ciq:xal:3&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink1&quot; xmlns:ct=&quot;urn:oasis:names:tc:ciq:ct:3&quot; targetNamespace=&quot;urn:oasis:names:tc:ciq:xal:3&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;xs:annotation&gt;
        ///		&lt;xs:documentation&gt; 
        ///		Specification Name: OASIS CIQ TC - extensible Address Language (xAL) 
        ///		Description: Defines the W3C schema for representing addresses
        ///		(U [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xAL {
            get {
                return ResourceManager.GetString("xAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;urn:oasis:names:tc:ciq:xal:3&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;urn:oasis:names:tc:ciq:xal:3&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;xs:annotation&gt;
        ///		&lt;xs:documentation&gt; 
        ///		Specification Name: OASIS CIQ TC - extensible AddressLanguage Types (xAL-types)
        ///		Description: Defines the W3C schema that provides enumeration lists to support xNL v3.0
        ///		(Using XML Schema based standard code list/enumera [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xAL_types {
            get {
                return ResourceManager.GetString("xAL_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- (c) XBRL International.  See www.xbrl.org/legal  
        /// XLink attribute specification - produced by xBRL group with joint design agreement with OASIS CIQ TC
        ///in December 2006
        ///    Thanks to xBRL for giving OASIS CIQ TC permission to use this specification
        ///--&gt;
        ///&lt;schema xmlns:xlink=&quot;http://www.w3.org/1999/xlink1&quot; xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.w3.org/1999/xlink1&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;annotat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xlink_2003_12_31 {
            get {
                return ResourceManager.GetString("xlink_2003_12_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- File: xlinks.xsd  --&gt;
        ///&lt;schema targetNamespace=&quot;http://www.w3.org/1999/xlink&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; version=&quot;2.0&quot;&gt;
        ///	&lt;annotation&gt;
        ///		&lt;appinfo source=&quot;urn:opengis:specification:gml:schema-xsd:xlinks:v3.0c2&quot;&gt;xlinks.xsd v3.0b2 2001-07&lt;/appinfo&gt;
        ///		&lt;documentation&gt;
        ///			GML 3.0 candidate xlinks schema. Copyright (c) 2001 OGC, All Rights Reserved.
        ///			
        ///			Edited 2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xlinks {
            get {
                return ResourceManager.GetString("xlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xal=&quot;urn:oasis:names:tc:ciq:xal:3&quot; xmlns:xnl=&quot;urn:oasis:names:tc:ciq:xnl:3&quot; xmlns=&quot;urn:oasis:names:tc:ciq:xnal:3&quot; xmlns:ct=&quot;urn:oasis:names:tc:ciq:ct:3&quot; targetNamespace=&quot;urn:oasis:names:tc:ciq:xnal:3&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;xs:annotation&gt;
        ///		&lt;xs:documentation&gt; 
        ///		Specification Name: OASIS CIQ TC - extensible Name and Address Language (xNAL) 
        ///		Description: Defin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xNAL {
            get {
                return ResourceManager.GetString("xNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;urn:oasis:names:tc:ciq:xnal:3&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;urn:oasis:names:tc:ciq:xnal:3&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;xs:annotation&gt;
        ///		&lt;xs:documentation&gt; 
        ///		Specification Name: OASIS CIQ TC - extensible Name and Address Language Types (xNAL-types)
        ///		Description: Defines the W3C schema that provides enumeration lists to support xNAL v3.0
        ///		(Using XML Schema based standard cod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xNAL_types {
            get {
                return ResourceManager.GetString("xNAL_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;urn:oasis:names:tc:ciq:xnl:3&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink1&quot; xmlns:ct=&quot;urn:oasis:names:tc:ciq:ct:3&quot; targetNamespace=&quot;urn:oasis:names:tc:ciq:xnl:3&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;xs:annotation&gt;
        ///		&lt;xs:documentation&gt; 
        ///		Specification Name: OASIS CIQ TC - extensible Name Language (xNL) 
        ///		Description: Defines the W3C schema for representing party names (Perso [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xNL {
            get {
                return ResourceManager.GetString("xNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;urn:oasis:names:tc:ciq:xnl:3&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;urn:oasis:names:tc:ciq:xnl:3&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;xs:annotation&gt;
        ///		&lt;xs:documentation&gt; 
        ///		Specification Name: OASIS CIQ TC - extensible Name Language Types (xNL-types)
        ///		Description: Defines the W3C schema that provides enumeration lists to support xNL v3.0
        ///		(Using XML Schema based standard code list/enumerati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xNL_types {
            get {
                return ResourceManager.GetString("xNL_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XMLSpy v2010 rel. 3 sp1 (x64) (http://www.altova.com) by Donald McGarry --&gt;
        ///&lt;xs:schema xmlns:a=&quot;urn:oasis:names:tc:ciq:xal:3&quot; xmlns:n=&quot;urn:oasis:names:tc:ciq:xnl:3&quot; xmlns=&quot;urn:oasis:names:tc:ciq:xpil:3&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink1&quot; xmlns:ct=&quot;urn:oasis:names:tc:ciq:ct:3&quot; targetNamespace=&quot;urn:oasis:names:tc:ciq:xpil:3&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;qua [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xPIL {
            get {
                return ResourceManager.GetString("xPIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;urn:oasis:names:tc:ciq:xpil:3&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;urn:oasis:names:tc:ciq:xpil:3&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;xs:annotation&gt;
        ///		&lt;xs:documentation&gt; 
        ///		Specification Name: OASIS CIQ TC - extensible Party Information Language Types (xPIL-types)
        ///		Description: Defines the W3C schema that provides enumeration lists to support
        ///		xPIL. 
        ///		(Using XML Schema based standard co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xPIL_types {
            get {
                return ResourceManager.GetString("xPIL_types", resourceCulture);
            }
        }
    }
}
