//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDXLSharp.CAPLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDXLSharp.CAPLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;urn:oasis:names:tc:emergency:cap:1.1&quot; xmlns:cap=&quot;urn:oasis:names:tc:emergency:cap:1.1&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///  &lt;element name=&quot;alert&quot;&gt;
        ///    &lt;annotation&gt;
        ///      &lt;documentation&gt;CAP Alert Message (version 1.1)&lt;/documentation&gt;
        ///    &lt;/annotation&gt;
        ///    &lt;complexType&gt;
        ///      &lt;sequence&gt;
        ///        &lt;element name=&quot;identifier&quot; ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CAP_v1_1 {
            get {
                return ResourceManager.GetString("CAP_v1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version = &quot;1.0&quot; encoding = &quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright OASIS Open 2010 All Rights Reserved --&gt;
        ///&lt;schema xmlns = &quot;http://www.w3.org/2001/XMLSchema&quot;
        ///   targetNamespace = &quot;urn:oasis:names:tc:emergency:cap:1.2&quot;
        ///   xmlns:cap = &quot;urn:oasis:names:tc:emergency:cap:1.2&quot;
        ///   xmlns:xs = &quot;http://www.w3.org/2001/XMLSchema&quot;
        ///   elementFormDefault = &quot;qualified&quot;
        ///   attributeFormDefault = &quot;unqualified&quot;
        ///   version = &quot;1.2&quot;&gt;
        ///  &lt;element name = &quot;alert&quot;&gt;
        ///    &lt;annotation&gt;
        ///      &lt;documentation&gt;CAP Alert Message (version 1.2)&lt;/docume [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CAP_v1_2_os {
            get {
                return ResourceManager.GetString("CAP_v1_2_os", resourceCulture);
            }
        }
    }
}
